### ISSUE TITLE
performance of Firefox with Sound Control and hundreds of tabs

### ISSUE THREAD

**Issue by grahamperrin** [kumar303/sound-control#10]
Firefox 56.0 (64-bit) on FreeBSD-CURRENT on a reasonably powerful notebook with 16 GB memory. At the time of writing: 908 tabs in around seventy-six groups across thirteen windows, with sixty-six tabs loaded. 

A short while ago, I followed a link from <http://fasezero.com/lastnotice.html> to <https://www.youtube.com/playlist?list=PLkWzvZH7LixZFCvGT2lt1MCzSST6Yetld> (probably a <kbd>Control</kbd>-Click, for the video in a new tab). Then the _play all_ option. 

YouTube presented an asynchronous progress indicator but the indicator soon ceased to spin and Firefox became somewhat unresponsive. Neither hogging the CPU nor thrashing the disk (virtual memory), just slow to respond. 

I had similar problems on past occasions, on this occasion I thought of Sound Control and – first impression – it seemed that disabling the extension almost immediately allowed Firefox to begin responding normally, and the video played. 

Thoughts? 

TIA

**Comment by grahamperrin** [comment]
> … similar problems on past occasions, on this occasion I thought of Sound Control and – first impression – it seemed that disabling the extension almost immediately allowed Firefox to begin responding normally, …

That was a one-off. 

It's likely that: 

- most test sessions, around that time, involved attention to a variety of extensions in each session
- simple coincidence caused me to wrongly suspect that Sound Control was contributory to problems. 

----

Later test sessions paid **greater attention to the order of things, sequences of actions**. Touch wood, no problem with Sound Control – 👍 it was, and remains, [a favourite](https://addons.mozilla.org/collections/grahamperrin/favorites/). 

I'll close this as **invalid**, not an issue with Sound Control. Instead: 

- [Firefox 56.0.1 performance problems with a featured extension - Firefox Development - Mozilla Discourse](https://discourse.mozilla.org/t/-/20463?u=grahamperrin)

**Comment by kumar303** [comment]
Hi. Thanks anyway for filing the issue. I wish these kind of regressions caused by add-ons were easier to track down.
